[build]
publish = "out"
command = "npm install --os=linux --cpu=x64 sharp && npm run build"

[functions]
included_files = ["src/content/**"]

[build.environment]
NODE_VERSION = "18"
__NEXT_PRIVATE_PREBUNDLED_REACT = "next"
# NEXT_FORCE_EDGE_IMAGES = true
NETLIFY_NEXT_PLUGIN_SKIP = "true"
NPM_VERSION = "8.19.2"

# [[headers]]
# for = "/*" # This defines which paths this specific [[headers]] block will cover.

# [headers.values]
# X-Frame-Options = "DENY"
# X-XSS-Protection = "1; mode=block"
# Referrer-Policy = "same-origin"
# Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
