# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: add-meme

on:
  pull_request:

permissions:
  contents: read

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - uses: webfactory/ssh-agent@v0.7.0
      with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY_MEME_GENERATOR }}
    - run: |
        git clone git@github.com:rebelastronaut/meme-generator.git
        echo "cloning"
        cd meme-generator
        git checkout testing
        ls -la
    - name: Install dependencies
      run: |
        cd meme-generator
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: make a meme
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        cd meme-generator
        ./meme-generator --output WEBP --openai-api-key ${OPENAI_API_KEY}
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: memes
        path: ./meme-generator/memes/